name: 'Swift Coverage Report'
description: 'Report SPM test coverage summary and lcov file'
author: 'Maxime Epain'
branding:
    icon: 'check-circle'  
    color: 'orange'
inputs:
    output-file:
        description: 'The output file path'
        required: false
        default: '.build/debug/codecov/lcov.info'
    file-format:
        description: 'The output file format'
        required: false
        default: 'lcov'
runs:
    using: 'node12'
    main: 'index.js'